version: '3'
services:
  flask:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 base:app --reload --timeout 90
    environment:
      - FLASK_APP=base.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root